User's Guide
------------

This part of the documentation will show you how to get started in using Mixer.

.. toctree::
   :maxdepth: 2

   installation
   quickstart
..   django
..   flask
..   sqlalchemy


API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api


Bug tracker
~~~~~~~~~~~

If you have any suggestions, bug reports or
annoyances please report them to the issue tracker
at https://github.com/klen/Mixer/issues


Contributing
~~~~~~~~~~~~

Development of mixer happens at github: https://github.com/klen/Mixer


Contributors
~~~~~~~~~~~~

* klen_ (Kirill Klenov)


License
~~~~~~~

Licensed under a `BSD license`_.


.. _BSD license: http://www.linfo.org/bsdlicense.html
.. _klen: http://klen.github.io/
