name: release

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 5

    - uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Build package
      run: |
        pip install wheel
        python setup.py bdist_wheel
        python setup.py sdist

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

    - name: Download a distribution artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypy }}

  notify:
    runs-on: ubuntu-latest
    needs: release
    steps:

    - name: Notify Success
      uses: archive/github-actions-slack@master
      with:
          slack-channel: C2CRL4C4V
          slack-text: Build is success *[${{ github.repository }}] (${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-optional-as_user: false
          slack-optional-icon_emoji: ":white_check_mark:"
